# Generated by Django 4.0.6 on 2022-07-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('S', 'Success'), ('F', 'Failed')], max_length=1),
        ),
    ]
