# Generated by Django 4.0.6 on 2022-07-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
        ('order', '0009_remove_orderitem_book_orderitem_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book'),
        ),
    ]
